add payment contract and dploy

diff --git a/contracts/Makefile b/contracts/Makefile
--- a/contracts/Makefile
+++ b/contracts/Makefile
@@ -67,3 +67,23 @@ deploy-token-dbc-mainnet:
 		echo "Error: .env file not found"; \
 		exit 1; \
 	fi
+
+deploy-token-payment-mainnet:
+	@if [ -f .env ]; then \
+		export $$(grep -v '^#' .env | xargs); \
+		forge script script/payment/Deploy.s.sol:Deploy \
+		--rpc-url $(dbc-mainnet) \
+		--private-key $(PRIVATE_KEY) \
+		--broadcast \
+		--verify \
+		--verifier blockscout \
+		--verifier-url $(MAIN_NET_VERIFIER_URL) \
+		--force \
+		--skip-simulation \
+		--legacy; \
+	else \
+		echo "Error: .env file not found"; \
+		exit 1; \
+	fi
+
+	source .env && forge script script/payment/Upgrade.s.sol:Upgrade --rpc-url dbc-mainnet --broadcast --verify --verifier blockscout --verifier-url $MAIN_NET_VERIFIER_URL --force --skip-simulation --legacy
